/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectvendingmachine;

import javax.swing.JFrame;

/**
 *
 * @author Sruti
 */
public class CalorieCountGUI extends javax.swing.JFrame {

   
    private GuiSubject subject;
    
     public CalorieCountGUI() {
     }
    /**
     * Creates new form CalorieCountGUI
     * @param subject
     */
    public CalorieCountGUI(GuiSubject subject) {
        initComponents();
        this.subject = subject;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        calorieGUIImagePanel = new javax.swing.JPanel();
        CalorieCountPanel = new javax.swing.JPanel();
        calorieCountLabel = new javax.swing.JLabel();
        CalorieTextField = new javax.swing.JTextField();
        okCalorieCountButton = new javax.swing.JButton();
        calorieSlider = new javax.swing.JSlider();
        calorieCountImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        calorieGUIImagePanel.setLayout(null);

        CalorieCountPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Calorie Count"));
        CalorieCountPanel.setOpaque(false);

        calorieCountLabel.setText("Enter the range of Calorie count (0 - 250)");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, calorieSlider, org.jdesktop.beansbinding.ELProperty.create("${value}"), CalorieTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        CalorieTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalorieTextFieldActionPerformed(evt);
            }
        });

        okCalorieCountButton.setText("Ok");
        okCalorieCountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okCalorieCountButtonActionPerformed(evt);
            }
        });

        calorieSlider.setMajorTickSpacing(50);
        calorieSlider.setMaximum(250);
        calorieSlider.setMinorTickSpacing(20);
        calorieSlider.setPaintLabels(true);
        calorieSlider.setPaintTicks(true);
        calorieSlider.setSnapToTicks(true);

        javax.swing.GroupLayout CalorieCountPanelLayout = new javax.swing.GroupLayout(CalorieCountPanel);
        CalorieCountPanel.setLayout(CalorieCountPanelLayout);
        CalorieCountPanelLayout.setHorizontalGroup(
            CalorieCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalorieCountPanelLayout.createSequentialGroup()
                .addGroup(CalorieCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalorieCountPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(CalorieCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calorieCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calorieSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CalorieCountPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(okCalorieCountButton))
                    .addGroup(CalorieCountPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(CalorieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        CalorieCountPanelLayout.setVerticalGroup(
            CalorieCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalorieCountPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(calorieCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calorieSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CalorieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okCalorieCountButton)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        calorieGUIImagePanel.add(CalorieCountPanel);
        CalorieCountPanel.setBounds(40, 60, 362, 257);

        calorieCountImageLabel.setIcon(new javax.swing.ImageIcon("/Users/Sruti/Desktop/images/blueBackground.jpg")); // NOI18N
        calorieGUIImagePanel.add(calorieCountImageLabel);
        calorieCountImageLabel.setBounds(-5, -4, 460, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calorieGUIImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calorieGUIImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalorieTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalorieTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalorieTextFieldActionPerformed

    private void okCalorieCountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okCalorieCountButtonActionPerformed
        // TODO add your handling code here:
        String Calories = CalorieTextField.getText();
        subject.setCalories(Calories);
        this.dispose();
    }//GEN-LAST:event_okCalorieCountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalorieCountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalorieCountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalorieCountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalorieCountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalorieCountGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CalorieCountPanel;
    private javax.swing.JTextField CalorieTextField;
    private javax.swing.JLabel calorieCountImageLabel;
    private javax.swing.JLabel calorieCountLabel;
    private javax.swing.JPanel calorieGUIImagePanel;
    private javax.swing.JSlider calorieSlider;
    private javax.swing.JButton okCalorieCountButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
