/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectvendingmachine;

/**
 *
 * @author Sruti
 */
public class PriceRangeGUI extends javax.swing.JFrame {

    /**
     * Creates new form PriceRangeGUI
     */
    private GuiSubject subject;
    
    public PriceRangeGUI() {
        
    }

     public PriceRangeGUI(GuiSubject subject) {
        initComponents();
       this.subject = subject;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        priceGuiImagePanel = new javax.swing.JPanel();
        priceRangePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        priceRangeTextField = new javax.swing.JTextField();
        priceRangeButton = new javax.swing.JButton();
        priceSlider = new javax.swing.JSlider();
        priceGuiImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        priceGuiImagePanel.setLayout(null);

        priceRangePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Price Range"));
        priceRangePanel.setOpaque(false);

        jLabel1.setText("Enter the price Range ( 1$ - 10$)");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, priceSlider, org.jdesktop.beansbinding.ELProperty.create("${value}"), priceRangeTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        priceRangeButton.setText("Ok");
        priceRangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceRangeButtonActionPerformed(evt);
            }
        });

        priceSlider.setMajorTickSpacing(1);
        priceSlider.setMaximum(10);
        priceSlider.setMinimum(1);
        priceSlider.setMinorTickSpacing(1);
        priceSlider.setPaintLabels(true);
        priceSlider.setPaintTicks(true);
        priceSlider.setSnapToTicks(true);

        javax.swing.GroupLayout priceRangePanelLayout = new javax.swing.GroupLayout(priceRangePanel);
        priceRangePanel.setLayout(priceRangePanelLayout);
        priceRangePanelLayout.setHorizontalGroup(
            priceRangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priceRangePanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(priceRangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(priceRangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(priceSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(priceRangePanelLayout.createSequentialGroup()
                            .addGroup(priceRangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(priceRangeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, priceRangePanelLayout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(priceRangeButton)))
                            .addGap(53, 53, 53)))
                    .addComponent(jLabel1))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        priceRangePanelLayout.setVerticalGroup(
            priceRangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priceRangePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priceSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priceRangeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(priceRangeButton)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        priceGuiImagePanel.add(priceRangePanel);
        priceRangePanel.setBounds(50, 50, 320, 250);

        priceGuiImageLabel.setIcon(new javax.swing.ImageIcon("/Users/Sruti/Desktop/images/blueBackground.jpg")); // NOI18N
        priceGuiImageLabel.setSize(new java.awt.Dimension(460, 380));
        priceGuiImagePanel.add(priceGuiImageLabel);
        priceGuiImageLabel.setBounds(-5, -4, 460, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(priceGuiImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(priceGuiImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priceRangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceRangeButtonActionPerformed
        // TODO add your handling code here:
        
         String price = priceRangeTextField.getText();
         System.out.println("GUI price text field value"+price);
        subject.setPrice(price);
        this.dispose();
    }//GEN-LAST:event_priceRangeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PriceRangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PriceRangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PriceRangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PriceRangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PriceRangeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel priceGuiImageLabel;
    private javax.swing.JPanel priceGuiImagePanel;
    private javax.swing.JButton priceRangeButton;
    private javax.swing.JPanel priceRangePanel;
    private javax.swing.JTextField priceRangeTextField;
    private javax.swing.JSlider priceSlider;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
