/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectvendingmachine;

import javax.swing.JOptionPane;

/**
 *
 * @author Sruti
 */
public class SugarContentGUI extends javax.swing.JFrame {

    
    private GuiSubject subject;
    
    /**
     * Creates new form SugarContentGUI
     */
    public SugarContentGUI() {
        
    }
    
    public SugarContentGUI(GuiSubject subject) {
        initComponents();
        this.subject = subject;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        SugarContentPanel = new javax.swing.JPanel();
        sugarContentLabel = new javax.swing.JLabel();
        lowSugarRadioButton = new javax.swing.JRadioButton();
        sugarContentButton = new javax.swing.JButton();
        mediumSugarRadioButton = new javax.swing.JRadioButton();
        highSugarRadioButton = new javax.swing.JRadioButton();
        lowRangeLabel = new javax.swing.JLabel();
        mediumRangeLabel = new javax.swing.JLabel();
        highRangeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sugarContentLabel.setText("Select the level of sugar content ");

        buttonGroup1.add(lowSugarRadioButton);
        lowSugarRadioButton.setText("Low");

        sugarContentButton.setText("Ok");
        sugarContentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sugarContentButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(mediumSugarRadioButton);
        mediumSugarRadioButton.setText("Medium");

        buttonGroup1.add(highSugarRadioButton);
        highSugarRadioButton.setText("High");

        lowRangeLabel.setText("(0 - 50)");

        mediumRangeLabel.setText("(51 - 100)");

        highRangeLabel.setText("(>100)");

        javax.swing.GroupLayout SugarContentPanelLayout = new javax.swing.GroupLayout(SugarContentPanel);
        SugarContentPanel.setLayout(SugarContentPanelLayout);
        SugarContentPanelLayout.setHorizontalGroup(
            SugarContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SugarContentPanelLayout.createSequentialGroup()
                .addGroup(SugarContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SugarContentPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(sugarContentButton))
                    .addGroup(SugarContentPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(SugarContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SugarContentPanelLayout.createSequentialGroup()
                                .addComponent(lowSugarRadioButton)
                                .addGap(26, 26, 26)
                                .addComponent(lowRangeLabel))
                            .addGroup(SugarContentPanelLayout.createSequentialGroup()
                                .addGroup(SugarContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mediumSugarRadioButton)
                                    .addComponent(highSugarRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SugarContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SugarContentPanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(highRangeLabel))
                                    .addComponent(mediumRangeLabel)))))
                    .addGroup(SugarContentPanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(sugarContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        SugarContentPanelLayout.setVerticalGroup(
            SugarContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SugarContentPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(sugarContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SugarContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lowSugarRadioButton)
                    .addComponent(lowRangeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SugarContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mediumSugarRadioButton)
                    .addComponent(mediumRangeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SugarContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(highSugarRadioButton)
                    .addComponent(highRangeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(sugarContentButton)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SugarContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(SugarContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sugarContentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sugarContentButtonActionPerformed
        // TODO add your handling code here:
        String sugars;
        if(highSugarRadioButton.isSelected()) {
            sugars = highSugarRadioButton.getText();
            subject.setSugars(sugars);
        } else if(mediumSugarRadioButton.isSelected()) {
            sugars = mediumSugarRadioButton.getText();
             subject.setSugars(sugars);
        } else if(lowSugarRadioButton.isSelected()) {
            sugars = lowSugarRadioButton.getText();
             subject.setSugars(sugars);
        } else {
             JOptionPane.showMessageDialog(null, " Select atleast one option ", "error messages", JOptionPane.ERROR_MESSAGE);
        }
        
        this.dispose();
        
    }//GEN-LAST:event_sugarContentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SugarContentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SugarContentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SugarContentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SugarContentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SugarContentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SugarContentPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel highRangeLabel;
    private javax.swing.JRadioButton highSugarRadioButton;
    private javax.swing.JLabel lowRangeLabel;
    private javax.swing.JRadioButton lowSugarRadioButton;
    private javax.swing.JLabel mediumRangeLabel;
    private javax.swing.JRadioButton mediumSugarRadioButton;
    private javax.swing.JButton sugarContentButton;
    private javax.swing.JLabel sugarContentLabel;
    // End of variables declaration//GEN-END:variables
}
