/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectvendingmachine;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Tonia
 */

public class VendingMachineGUI extends javax.swing.JFrame {

    private GuiSubject subject;
    double SmartCardPrice = 0; 
    /**
     * Creates new form VendingMachineGUI
     */
    public VendingMachineGUI() {
        initComponents();
        subject = new GuiSubject();
       
    }
    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        requirementsPanel = new javax.swing.JPanel();
        cbCalorieCount = new javax.swing.JCheckBox();
        cbSugarContent = new javax.swing.JCheckBox();
        cbFatContent = new javax.swing.JCheckBox();
        cbPriceRange = new javax.swing.JCheckBox();
        cbFoodType = new javax.swing.JCheckBox();
        btnProceed = new javax.swing.JButton();
        adminLoginButton = new javax.swing.JButton();
        buySmartCardPanel = new javax.swing.JPanel();
        smart10RadioButton = new javax.swing.JRadioButton();
        smart20RadioButton = new javax.swing.JRadioButton();
        smart50RadioButton = new javax.swing.JRadioButton();
        smartCardCheckOutButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        titlePanel.setOpaque(false);

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N

        welcomeLabel.setText("Welcome  ");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(welcomeLabel))
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(titleLabel)))
                .addContainerGap(388, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(welcomeLabel)
                .addContainerGap())
        );

        jPanel2.add(titlePanel);
        titlePanel.setBounds(10, 0, 629, 40);

        requirementsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose your options"));
        requirementsPanel.setOpaque(false);

        cbCalorieCount.setText("Calorie Count");
        cbCalorieCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCalorieCountActionPerformed(evt);
            }
        });

        cbSugarContent.setText("Sugar Content");
        cbSugarContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSugarContentActionPerformed(evt);
            }
        });

        cbFatContent.setText("Fat Content");
        cbFatContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFatContentActionPerformed(evt);
            }
        });

        cbPriceRange.setText("Price Range ");
        cbPriceRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPriceRangeActionPerformed(evt);
            }
        });

        cbFoodType.setText("Food Type");
        cbFoodType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFoodTypeActionPerformed(evt);
            }
        });

        btnProceed.setText("Proceed");
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout requirementsPanelLayout = new javax.swing.GroupLayout(requirementsPanel);
        requirementsPanel.setLayout(requirementsPanelLayout);
        requirementsPanelLayout.setHorizontalGroup(
            requirementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requirementsPanelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(requirementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(requirementsPanelLayout.createSequentialGroup()
                        .addGroup(requirementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSugarContent)
                            .addComponent(cbCalorieCount)
                            .addComponent(cbFatContent)
                            .addComponent(cbPriceRange))
                        .addContainerGap(299, Short.MAX_VALUE))
                    .addGroup(requirementsPanelLayout.createSequentialGroup()
                        .addComponent(cbFoodType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProceed)
                        .addGap(107, 107, 107))))
        );
        requirementsPanelLayout.setVerticalGroup(
            requirementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requirementsPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(cbCalorieCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbSugarContent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbFatContent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPriceRange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(requirementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFoodType)
                    .addComponent(btnProceed))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.add(requirementsPanel);
        requirementsPanel.setBounds(20, 80, 560, 230);

        adminLoginButton.setText("Admin Login");
        adminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(adminLoginButton);
        adminLoginButton.setBounds(490, 500, 124, 29);

        buySmartCardPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose SmartCard"));
        buySmartCardPanel.setOpaque(false);

        buttonGroup1.add(smart10RadioButton);
        smart10RadioButton.setText("Smart10");
        smart10RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smart10RadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(smart20RadioButton);
        smart20RadioButton.setText("Smart20");
        smart20RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smart20RadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(smart50RadioButton);
        smart50RadioButton.setText("Smart50");
        smart50RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smart50RadioButtonActionPerformed(evt);
            }
        });

        smartCardCheckOutButton.setText("CheckOut");
        smartCardCheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smartCardCheckOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buySmartCardPanelLayout = new javax.swing.GroupLayout(buySmartCardPanel);
        buySmartCardPanel.setLayout(buySmartCardPanelLayout);
        buySmartCardPanelLayout.setHorizontalGroup(
            buySmartCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buySmartCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(smart10RadioButton)
                .addGap(38, 38, 38)
                .addComponent(smart20RadioButton)
                .addGap(34, 34, 34)
                .addComponent(smart50RadioButton)
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buySmartCardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(smartCardCheckOutButton)
                .addGap(91, 91, 91))
        );
        buySmartCardPanelLayout.setVerticalGroup(
            buySmartCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buySmartCardPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(buySmartCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smart10RadioButton)
                    .addComponent(smart20RadioButton)
                    .addComponent(smart50RadioButton))
                .addGap(18, 18, 18)
                .addComponent(smartCardCheckOutButton)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2.add(buySmartCardPanel);
        buySmartCardPanel.setBounds(20, 320, 560, 170);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/Sruti/Desktop/images/background.jpeg")); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 670, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCalorieCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCalorieCountActionPerformed
        // TODO add your handling code here:
        if(cbCalorieCount.isSelected()) {
            new CalorieCountGUI(subject).setVisible(true);
        }
        
    }//GEN-LAST:event_cbCalorieCountActionPerformed

    private void cbSugarContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSugarContentActionPerformed
        // TODO add your handling code here:
        if(cbSugarContent.isSelected()) {
            new SugarContentGUI(subject).setVisible(true);
        }
    }//GEN-LAST:event_cbSugarContentActionPerformed

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        // TODO add your handling code here:
        
        boolean[] arr = new boolean[5];
        if(!(cbCalorieCount.isSelected()|| cbSugarContent.isSelected()|| cbFatContent.isSelected() || 
                cbPriceRange.isSelected() || cbFoodType.isSelected())) {
            JOptionPane.showMessageDialog(null, " Select atleast one checkbox ", "error messages", JOptionPane.ERROR_MESSAGE);
        } else {
           
            arr[0] = cbCalorieCount.isSelected();
            arr[1] = cbSugarContent.isSelected();
            arr[2] = cbFatContent.isSelected();
            arr[3] = cbPriceRange.isSelected();
            arr[4] = cbFoodType.isSelected();
            
            subject.notifyObserver(arr);
            //new CartGUI().setVisible(true);
            this.dispose();
        }
        
        
    }//GEN-LAST:event_btnProceedActionPerformed

    private void cbFatContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFatContentActionPerformed
        // TODO add your handling code here:
        if(cbFatContent.isSelected()) {
            new FatContentGUI(subject).setVisible(true);
        }
    }//GEN-LAST:event_cbFatContentActionPerformed

    private void cbPriceRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPriceRangeActionPerformed
        // TODO add your handling code here:
        if(cbPriceRange.isSelected()) {
            new PriceRangeGUI(subject).setVisible(true);
        }
    }//GEN-LAST:event_cbPriceRangeActionPerformed

    private void cbFoodTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFoodTypeActionPerformed
        // TODO add your handling code here:
        if(cbFoodType.isSelected()) {
            new FoodTypeGUI(subject).setVisible(true);
        }
    }//GEN-LAST:event_cbFoodTypeActionPerformed

    private void smartCardCheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smartCardCheckOutButtonActionPerformed
        try {
            // TODO add your handling code here:
          new PaymentGUI(Double.toString(SmartCardPrice),"BuySmartCard",null).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(VendingMachineGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_smartCardCheckOutButtonActionPerformed

    private void smart10RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smart10RadioButtonActionPerformed
        // TODO add your handling code here:
        if(smart10RadioButton.isSelected()) {
            SmartCardPrice = 10.0;
        }
    }//GEN-LAST:event_smart10RadioButtonActionPerformed

    private void smart20RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smart20RadioButtonActionPerformed
        // TODO add your handling code here:
        if(smart20RadioButton.isSelected()) {
            SmartCardPrice = 20.0;
        }
    }//GEN-LAST:event_smart20RadioButtonActionPerformed

    private void smart50RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smart50RadioButtonActionPerformed
        // TODO add your handling code here:
        if(smart50RadioButton.isSelected()) {
            SmartCardPrice = 50.0;
        }
    }//GEN-LAST:event_smart50RadioButtonActionPerformed

    private void adminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginButtonActionPerformed
        new LoginGUI().setVisible(true);
    }//GEN-LAST:event_adminLoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendingMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendingMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendingMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendingMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendingMachineGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminLoginButton;
    private javax.swing.JButton btnProceed;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel buySmartCardPanel;
    private javax.swing.JCheckBox cbCalorieCount;
    private javax.swing.JCheckBox cbFatContent;
    private javax.swing.JCheckBox cbFoodType;
    private javax.swing.JCheckBox cbPriceRange;
    private javax.swing.JCheckBox cbSugarContent;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel requirementsPanel;
    private javax.swing.JRadioButton smart10RadioButton;
    private javax.swing.JRadioButton smart20RadioButton;
    private javax.swing.JRadioButton smart50RadioButton;
    private javax.swing.JButton smartCardCheckOutButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}


